### ISSUE TITLE
HELP WANTED!!!!!!

### ISSUE THREAD

**Issue by frank226399** [frank226399/read-me#2]
Can any one help me

**Comment by DPS0340** [comment]
For what help?

**Comment by frank226399** [comment]
Coding

**Comment by DPS0340** [comment]
What's your plan? language, library, what you'll make, etc..

**Comment by frank226399** [comment]
Library

**Comment by DPS0340** [comment]
Please give me some detailed explanation.

**Comment by frank226399** [comment]
Well, i just started coding, and i want to learn how to code.

**Comment by DPS0340** [comment]
Ok. How can i help you? give some resources? need some guide?

**Comment by frank226399** [comment]
I need some guide

**Comment by frank226399** [comment]
Aalsdkjjfhgjfhgjfha;dskjfa;akdadfjkahhgjfa;s

**Comment by yeltsinxyz** [comment]
You can follow these roadmap or paths provided by [FreeCodeCamp](https://www.freecodecamp.org/news/2019-web-developer-roadmap/). It may helps you find the best guides :)

**Comment by DPS0340** [comment]
Check also:

[ossu](https://github.com/ossu/computer-science)

[Best websites a programmer should visit](https://github.com/sdmg15/Best-websites-a-programmer-should-visit)

[Free programming books/courses](https://github.com/EbookFoundation/free-programming-books)
